spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist_db
    username: your_database_name
    password:  your_database_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
